# Generated by Django 3.1.1 on 2020-09-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20200921_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='hand_over_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
