# Generated by Django 3.1.4 on 2020-12-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20201210_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='homeworkComment',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='homework',
        ),
        migrations.AddField(
            model_name='answer',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.homework'),
        ),
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.subject'),
        ),
        migrations.AddField(
            model_name='homeworkcomment',
            name='homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.homework'),
        ),
    ]
