# Generated by Django 3.1.4 on 2020-12-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0011_auto_20201213_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='colors',
            new_name='color',
        ),
    ]
